package parser

// Code generated by ../../../peg/peg -switch -inline -strict -output grammer.peg.go grammer.peg DO NOT EDIT.

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleUnit
	ruleCreatePackageDeclaration
	ruleIdentifier
	ruleLetter
	ruleSpacing
	ruleLetterOrDigit
	ruleKeyword
	ruleCREATE
	ruleOR
	ruleREPLACE
	rulePACKAGE
	ruleIS
	ruleEND
	ruleSEMI
	ruleEOT
)

var rul3s = [...]string{
	"Unknown",
	"Unit",
	"CreatePackageDeclaration",
	"Identifier",
	"Letter",
	"Spacing",
	"LetterOrDigit",
	"Keyword",
	"CREATE",
	"OR",
	"REPLACE",
	"PACKAGE",
	"IS",
	"END",
	"SEMI",
	"EOT",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type SqlParser struct {
	Buffer         string
	buffer         []rune
	rules          [16]func() bool
	parse          func(rule ...int) error
	reset          func()
	Pretty         bool
	disableMemoize bool
	tokens32
}

func (p *SqlParser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *SqlParser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *SqlParser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *SqlParser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *SqlParser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *SqlParser) SprintSyntaxTree() string {
	var b bytes.Buffer
	p.WriteSyntaxTree(&b)
	return b.String()
}

func Pretty(pretty bool) func(*SqlParser) error {
	return func(p *SqlParser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*SqlParser) error {
	return func(p *SqlParser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}

func DisableMemoize() func(*SqlParser) error {
	return func(p *SqlParser) error {
		p.disableMemoize = true
		return nil
	}
}

type memo struct {
	Matched bool
	Partial []token32
}

type memoKey struct {
	Rule     uint32
	Position uint32
}

func (p *SqlParser) Init(options ...func(*SqlParser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
		memoization          map[memoKey]memo
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0
		memoization = make(map[memoKey]memo)
		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	memoize := func(rule uint32, begin uint32, tokenIndexStart uint32, matched bool) {
		if p.disableMemoize {
			return
		}
		key := memoKey{rule, begin}
		if !matched {
			memoization[key] = memo{Matched: false}
		} else {
			t := tree.tree[tokenIndexStart:tokenIndex]
			tokenCopy := make([]token32, len(t))
			copy(tokenCopy, t)
			memoization[key] = memo{Matched: true, Partial: tokenCopy}
		}
	}

	memoizedResult := func(m memo) bool {
		if !m.Matched {
			return false
		}
		tree.tree = append(tree.tree[:tokenIndex], m.Partial...)
		tokenIndex += uint32(len(m.Partial))
		position = m.Partial[len(m.Partial)-1].end
		if tree.tree[tokenIndex-1].begin != position && position > max.end {
			max = tree.tree[tokenIndex-1]
		}
		return true
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Unit <- <(Spacing CreatePackageDeclaration EOT)> */
		func() bool {
			if memoized, ok := memoization[memoKey{0, position}]; ok {
				return memoizedResult(memoized)
			}
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleSpacing]() {
					goto l0
				}
				{
					position2 := position
					{
						position3 := position
						{
							position4, tokenIndex4 := position, tokenIndex
							if buffer[position] != rune('c') {
								goto l5
							}
							position++
							goto l4
						l5:
							position, tokenIndex = position4, tokenIndex4
							if buffer[position] != rune('C') {
								goto l0
							}
							position++
						}
					l4:
						{
							position6, tokenIndex6 := position, tokenIndex
							if buffer[position] != rune('r') {
								goto l7
							}
							position++
							goto l6
						l7:
							position, tokenIndex = position6, tokenIndex6
							if buffer[position] != rune('R') {
								goto l0
							}
							position++
						}
					l6:
						{
							position8, tokenIndex8 := position, tokenIndex
							if buffer[position] != rune('e') {
								goto l9
							}
							position++
							goto l8
						l9:
							position, tokenIndex = position8, tokenIndex8
							if buffer[position] != rune('E') {
								goto l0
							}
							position++
						}
					l8:
						{
							position10, tokenIndex10 := position, tokenIndex
							if buffer[position] != rune('a') {
								goto l11
							}
							position++
							goto l10
						l11:
							position, tokenIndex = position10, tokenIndex10
							if buffer[position] != rune('A') {
								goto l0
							}
							position++
						}
					l10:
						{
							position12, tokenIndex12 := position, tokenIndex
							if buffer[position] != rune('t') {
								goto l13
							}
							position++
							goto l12
						l13:
							position, tokenIndex = position12, tokenIndex12
							if buffer[position] != rune('T') {
								goto l0
							}
							position++
						}
					l12:
						{
							position14, tokenIndex14 := position, tokenIndex
							if buffer[position] != rune('e') {
								goto l15
							}
							position++
							goto l14
						l15:
							position, tokenIndex = position14, tokenIndex14
							if buffer[position] != rune('E') {
								goto l0
							}
							position++
						}
					l14:
						{
							position16, tokenIndex16 := position, tokenIndex
							if !_rules[ruleLetterOrDigit]() {
								goto l16
							}
							goto l0
						l16:
							position, tokenIndex = position16, tokenIndex16
						}
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(ruleCREATE, position3)
					}
					{
						position17, tokenIndex17 := position, tokenIndex
						{
							position19 := position
							{
								position20, tokenIndex20 := position, tokenIndex
								if buffer[position] != rune('o') {
									goto l21
								}
								position++
								goto l20
							l21:
								position, tokenIndex = position20, tokenIndex20
								if buffer[position] != rune('O') {
									goto l17
								}
								position++
							}
						l20:
							{
								position22, tokenIndex22 := position, tokenIndex
								if buffer[position] != rune('r') {
									goto l23
								}
								position++
								goto l22
							l23:
								position, tokenIndex = position22, tokenIndex22
								if buffer[position] != rune('R') {
									goto l17
								}
								position++
							}
						l22:
							{
								position24, tokenIndex24 := position, tokenIndex
								if !_rules[ruleLetterOrDigit]() {
									goto l24
								}
								goto l17
							l24:
								position, tokenIndex = position24, tokenIndex24
							}
							if !_rules[ruleSpacing]() {
								goto l17
							}
							add(ruleOR, position19)
						}
						{
							position25 := position
							{
								position26, tokenIndex26 := position, tokenIndex
								if buffer[position] != rune('r') {
									goto l27
								}
								position++
								goto l26
							l27:
								position, tokenIndex = position26, tokenIndex26
								if buffer[position] != rune('R') {
									goto l17
								}
								position++
							}
						l26:
							{
								position28, tokenIndex28 := position, tokenIndex
								if buffer[position] != rune('e') {
									goto l29
								}
								position++
								goto l28
							l29:
								position, tokenIndex = position28, tokenIndex28
								if buffer[position] != rune('E') {
									goto l17
								}
								position++
							}
						l28:
							{
								position30, tokenIndex30 := position, tokenIndex
								if buffer[position] != rune('p') {
									goto l31
								}
								position++
								goto l30
							l31:
								position, tokenIndex = position30, tokenIndex30
								if buffer[position] != rune('P') {
									goto l17
								}
								position++
							}
						l30:
							{
								position32, tokenIndex32 := position, tokenIndex
								if buffer[position] != rune('l') {
									goto l33
								}
								position++
								goto l32
							l33:
								position, tokenIndex = position32, tokenIndex32
								if buffer[position] != rune('L') {
									goto l17
								}
								position++
							}
						l32:
							{
								position34, tokenIndex34 := position, tokenIndex
								if buffer[position] != rune('a') {
									goto l35
								}
								position++
								goto l34
							l35:
								position, tokenIndex = position34, tokenIndex34
								if buffer[position] != rune('A') {
									goto l17
								}
								position++
							}
						l34:
							{
								position36, tokenIndex36 := position, tokenIndex
								if buffer[position] != rune('c') {
									goto l37
								}
								position++
								goto l36
							l37:
								position, tokenIndex = position36, tokenIndex36
								if buffer[position] != rune('C') {
									goto l17
								}
								position++
							}
						l36:
							{
								position38, tokenIndex38 := position, tokenIndex
								if buffer[position] != rune('e') {
									goto l39
								}
								position++
								goto l38
							l39:
								position, tokenIndex = position38, tokenIndex38
								if buffer[position] != rune('E') {
									goto l17
								}
								position++
							}
						l38:
							{
								position40, tokenIndex40 := position, tokenIndex
								if !_rules[ruleLetterOrDigit]() {
									goto l40
								}
								goto l17
							l40:
								position, tokenIndex = position40, tokenIndex40
							}
							if !_rules[ruleSpacing]() {
								goto l17
							}
							add(ruleREPLACE, position25)
						}
						goto l18
					l17:
						position, tokenIndex = position17, tokenIndex17
					}
				l18:
					{
						position41 := position
						{
							position42, tokenIndex42 := position, tokenIndex
							if buffer[position] != rune('p') {
								goto l43
							}
							position++
							goto l42
						l43:
							position, tokenIndex = position42, tokenIndex42
							if buffer[position] != rune('P') {
								goto l0
							}
							position++
						}
					l42:
						{
							position44, tokenIndex44 := position, tokenIndex
							if buffer[position] != rune('a') {
								goto l45
							}
							position++
							goto l44
						l45:
							position, tokenIndex = position44, tokenIndex44
							if buffer[position] != rune('A') {
								goto l0
							}
							position++
						}
					l44:
						{
							position46, tokenIndex46 := position, tokenIndex
							if buffer[position] != rune('c') {
								goto l47
							}
							position++
							goto l46
						l47:
							position, tokenIndex = position46, tokenIndex46
							if buffer[position] != rune('C') {
								goto l0
							}
							position++
						}
					l46:
						{
							position48, tokenIndex48 := position, tokenIndex
							if buffer[position] != rune('k') {
								goto l49
							}
							position++
							goto l48
						l49:
							position, tokenIndex = position48, tokenIndex48
							if buffer[position] != rune('K') {
								goto l0
							}
							position++
						}
					l48:
						{
							position50, tokenIndex50 := position, tokenIndex
							if buffer[position] != rune('a') {
								goto l51
							}
							position++
							goto l50
						l51:
							position, tokenIndex = position50, tokenIndex50
							if buffer[position] != rune('A') {
								goto l0
							}
							position++
						}
					l50:
						{
							position52, tokenIndex52 := position, tokenIndex
							if buffer[position] != rune('g') {
								goto l53
							}
							position++
							goto l52
						l53:
							position, tokenIndex = position52, tokenIndex52
							if buffer[position] != rune('G') {
								goto l0
							}
							position++
						}
					l52:
						{
							position54, tokenIndex54 := position, tokenIndex
							if buffer[position] != rune('e') {
								goto l55
							}
							position++
							goto l54
						l55:
							position, tokenIndex = position54, tokenIndex54
							if buffer[position] != rune('E') {
								goto l0
							}
							position++
						}
					l54:
						{
							position56, tokenIndex56 := position, tokenIndex
							if !_rules[ruleLetterOrDigit]() {
								goto l56
							}
							goto l0
						l56:
							position, tokenIndex = position56, tokenIndex56
						}
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(rulePACKAGE, position41)
					}
					{
						position57 := position
						{
							position58, tokenIndex58 := position, tokenIndex
							{
								position59 := position
								{
									switch buffer[position] {
									case 'E', 'e':
										{
											position61, tokenIndex61 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l62
											}
											position++
											goto l61
										l62:
											position, tokenIndex = position61, tokenIndex61
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l61:
										{
											position63, tokenIndex63 := position, tokenIndex
											if buffer[position] != rune('n') {
												goto l64
											}
											position++
											goto l63
										l64:
											position, tokenIndex = position63, tokenIndex63
											if buffer[position] != rune('N') {
												goto l58
											}
											position++
										}
									l63:
										{
											position65, tokenIndex65 := position, tokenIndex
											if buffer[position] != rune('d') {
												goto l66
											}
											position++
											goto l65
										l66:
											position, tokenIndex = position65, tokenIndex65
											if buffer[position] != rune('D') {
												goto l58
											}
											position++
										}
									l65:
										break
									case 'I', 'i':
										{
											position67, tokenIndex67 := position, tokenIndex
											if buffer[position] != rune('i') {
												goto l68
											}
											position++
											goto l67
										l68:
											position, tokenIndex = position67, tokenIndex67
											if buffer[position] != rune('I') {
												goto l58
											}
											position++
										}
									l67:
										{
											position69, tokenIndex69 := position, tokenIndex
											if buffer[position] != rune('s') {
												goto l70
											}
											position++
											goto l69
										l70:
											position, tokenIndex = position69, tokenIndex69
											if buffer[position] != rune('S') {
												goto l58
											}
											position++
										}
									l69:
										break
									case 'P', 'p':
										{
											position71, tokenIndex71 := position, tokenIndex
											if buffer[position] != rune('p') {
												goto l72
											}
											position++
											goto l71
										l72:
											position, tokenIndex = position71, tokenIndex71
											if buffer[position] != rune('P') {
												goto l58
											}
											position++
										}
									l71:
										{
											position73, tokenIndex73 := position, tokenIndex
											if buffer[position] != rune('a') {
												goto l74
											}
											position++
											goto l73
										l74:
											position, tokenIndex = position73, tokenIndex73
											if buffer[position] != rune('A') {
												goto l58
											}
											position++
										}
									l73:
										{
											position75, tokenIndex75 := position, tokenIndex
											if buffer[position] != rune('c') {
												goto l76
											}
											position++
											goto l75
										l76:
											position, tokenIndex = position75, tokenIndex75
											if buffer[position] != rune('C') {
												goto l58
											}
											position++
										}
									l75:
										{
											position77, tokenIndex77 := position, tokenIndex
											if buffer[position] != rune('k') {
												goto l78
											}
											position++
											goto l77
										l78:
											position, tokenIndex = position77, tokenIndex77
											if buffer[position] != rune('K') {
												goto l58
											}
											position++
										}
									l77:
										{
											position79, tokenIndex79 := position, tokenIndex
											if buffer[position] != rune('a') {
												goto l80
											}
											position++
											goto l79
										l80:
											position, tokenIndex = position79, tokenIndex79
											if buffer[position] != rune('A') {
												goto l58
											}
											position++
										}
									l79:
										{
											position81, tokenIndex81 := position, tokenIndex
											if buffer[position] != rune('g') {
												goto l82
											}
											position++
											goto l81
										l82:
											position, tokenIndex = position81, tokenIndex81
											if buffer[position] != rune('G') {
												goto l58
											}
											position++
										}
									l81:
										{
											position83, tokenIndex83 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l84
											}
											position++
											goto l83
										l84:
											position, tokenIndex = position83, tokenIndex83
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l83:
										break
									case 'R', 'r':
										{
											position85, tokenIndex85 := position, tokenIndex
											if buffer[position] != rune('r') {
												goto l86
											}
											position++
											goto l85
										l86:
											position, tokenIndex = position85, tokenIndex85
											if buffer[position] != rune('R') {
												goto l58
											}
											position++
										}
									l85:
										{
											position87, tokenIndex87 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l88
											}
											position++
											goto l87
										l88:
											position, tokenIndex = position87, tokenIndex87
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l87:
										{
											position89, tokenIndex89 := position, tokenIndex
											if buffer[position] != rune('p') {
												goto l90
											}
											position++
											goto l89
										l90:
											position, tokenIndex = position89, tokenIndex89
											if buffer[position] != rune('P') {
												goto l58
											}
											position++
										}
									l89:
										{
											position91, tokenIndex91 := position, tokenIndex
											if buffer[position] != rune('l') {
												goto l92
											}
											position++
											goto l91
										l92:
											position, tokenIndex = position91, tokenIndex91
											if buffer[position] != rune('L') {
												goto l58
											}
											position++
										}
									l91:
										{
											position93, tokenIndex93 := position, tokenIndex
											if buffer[position] != rune('a') {
												goto l94
											}
											position++
											goto l93
										l94:
											position, tokenIndex = position93, tokenIndex93
											if buffer[position] != rune('A') {
												goto l58
											}
											position++
										}
									l93:
										{
											position95, tokenIndex95 := position, tokenIndex
											if buffer[position] != rune('c') {
												goto l96
											}
											position++
											goto l95
										l96:
											position, tokenIndex = position95, tokenIndex95
											if buffer[position] != rune('C') {
												goto l58
											}
											position++
										}
									l95:
										{
											position97, tokenIndex97 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l98
											}
											position++
											goto l97
										l98:
											position, tokenIndex = position97, tokenIndex97
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l97:
										break
									case 'O', 'o':
										{
											position99, tokenIndex99 := position, tokenIndex
											if buffer[position] != rune('o') {
												goto l100
											}
											position++
											goto l99
										l100:
											position, tokenIndex = position99, tokenIndex99
											if buffer[position] != rune('O') {
												goto l58
											}
											position++
										}
									l99:
										{
											position101, tokenIndex101 := position, tokenIndex
											if buffer[position] != rune('r') {
												goto l102
											}
											position++
											goto l101
										l102:
											position, tokenIndex = position101, tokenIndex101
											if buffer[position] != rune('R') {
												goto l58
											}
											position++
										}
									l101:
										break
									default:
										{
											position103, tokenIndex103 := position, tokenIndex
											if buffer[position] != rune('c') {
												goto l104
											}
											position++
											goto l103
										l104:
											position, tokenIndex = position103, tokenIndex103
											if buffer[position] != rune('C') {
												goto l58
											}
											position++
										}
									l103:
										{
											position105, tokenIndex105 := position, tokenIndex
											if buffer[position] != rune('r') {
												goto l106
											}
											position++
											goto l105
										l106:
											position, tokenIndex = position105, tokenIndex105
											if buffer[position] != rune('R') {
												goto l58
											}
											position++
										}
									l105:
										{
											position107, tokenIndex107 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l108
											}
											position++
											goto l107
										l108:
											position, tokenIndex = position107, tokenIndex107
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l107:
										{
											position109, tokenIndex109 := position, tokenIndex
											if buffer[position] != rune('a') {
												goto l110
											}
											position++
											goto l109
										l110:
											position, tokenIndex = position109, tokenIndex109
											if buffer[position] != rune('A') {
												goto l58
											}
											position++
										}
									l109:
										{
											position111, tokenIndex111 := position, tokenIndex
											if buffer[position] != rune('t') {
												goto l112
											}
											position++
											goto l111
										l112:
											position, tokenIndex = position111, tokenIndex111
											if buffer[position] != rune('T') {
												goto l58
											}
											position++
										}
									l111:
										{
											position113, tokenIndex113 := position, tokenIndex
											if buffer[position] != rune('e') {
												goto l114
											}
											position++
											goto l113
										l114:
											position, tokenIndex = position113, tokenIndex113
											if buffer[position] != rune('E') {
												goto l58
											}
											position++
										}
									l113:
										break
									}
								}

								{
									position115, tokenIndex115 := position, tokenIndex
									if !_rules[ruleLetterOrDigit]() {
										goto l115
									}
									goto l58
								l115:
									position, tokenIndex = position115, tokenIndex115
								}
								add(ruleKeyword, position59)
							}
							goto l0
						l58:
							position, tokenIndex = position58, tokenIndex58
						}
						{
							position116 := position
							{
								switch buffer[position] {
								case '$', '_':
									{
										position118, tokenIndex118 := position, tokenIndex
										if buffer[position] != rune('_') {
											goto l119
										}
										position++
										goto l118
									l119:
										position, tokenIndex = position118, tokenIndex118
										if buffer[position] != rune('$') {
											goto l0
										}
										position++
									}
								l118:
									break
								case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
									if c := buffer[position]; c < rune('A') || c > rune('Z') {
										goto l0
									}
									position++
								default:
									if c := buffer[position]; c < rune('a') || c > rune('z') {
										goto l0
									}
									position++
								}
							}

							add(ruleLetter, position116)
						}
					l120:
						{
							position121, tokenIndex121 := position, tokenIndex
							if !_rules[ruleLetterOrDigit]() {
								goto l121
							}
							goto l120
						l121:
							position, tokenIndex = position121, tokenIndex121
						}
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(ruleIdentifier, position57)
					}
					{
						position122 := position
						{
							position123, tokenIndex123 := position, tokenIndex
							if buffer[position] != rune('i') {
								goto l124
							}
							position++
							goto l123
						l124:
							position, tokenIndex = position123, tokenIndex123
							if buffer[position] != rune('I') {
								goto l0
							}
							position++
						}
					l123:
						{
							position125, tokenIndex125 := position, tokenIndex
							if buffer[position] != rune('s') {
								goto l126
							}
							position++
							goto l125
						l126:
							position, tokenIndex = position125, tokenIndex125
							if buffer[position] != rune('S') {
								goto l0
							}
							position++
						}
					l125:
						{
							position127, tokenIndex127 := position, tokenIndex
							if !_rules[ruleLetterOrDigit]() {
								goto l127
							}
							goto l0
						l127:
							position, tokenIndex = position127, tokenIndex127
						}
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(ruleIS, position122)
					}
					{
						position128 := position
						{
							position129, tokenIndex129 := position, tokenIndex
							if buffer[position] != rune('e') {
								goto l130
							}
							position++
							goto l129
						l130:
							position, tokenIndex = position129, tokenIndex129
							if buffer[position] != rune('E') {
								goto l0
							}
							position++
						}
					l129:
						{
							position131, tokenIndex131 := position, tokenIndex
							if buffer[position] != rune('n') {
								goto l132
							}
							position++
							goto l131
						l132:
							position, tokenIndex = position131, tokenIndex131
							if buffer[position] != rune('N') {
								goto l0
							}
							position++
						}
					l131:
						{
							position133, tokenIndex133 := position, tokenIndex
							if buffer[position] != rune('d') {
								goto l134
							}
							position++
							goto l133
						l134:
							position, tokenIndex = position133, tokenIndex133
							if buffer[position] != rune('D') {
								goto l0
							}
							position++
						}
					l133:
						{
							position135, tokenIndex135 := position, tokenIndex
							if !_rules[ruleLetterOrDigit]() {
								goto l135
							}
							goto l0
						l135:
							position, tokenIndex = position135, tokenIndex135
						}
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(ruleEND, position128)
					}
					{
						position136 := position
						if buffer[position] != rune(';') {
							goto l0
						}
						position++
						if !_rules[ruleSpacing]() {
							goto l0
						}
						add(ruleSEMI, position136)
					}
					add(ruleCreatePackageDeclaration, position2)
				}
				{
					position137 := position
					{
						position138, tokenIndex138 := position, tokenIndex
						if !matchDot() {
							goto l138
						}
						goto l0
					l138:
						position, tokenIndex = position138, tokenIndex138
					}
					add(ruleEOT, position137)
				}
				add(ruleUnit, position1)
			}
			memoize(0, position0, tokenIndex0, true)
			return true
		l0:
			memoize(0, position0, tokenIndex0, false)
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 CreatePackageDeclaration <- <(CREATE (OR REPLACE)? PACKAGE Identifier IS END SEMI)> */
		nil,
		/* 2 Identifier <- <(!Keyword Letter LetterOrDigit* Spacing)> */
		nil,
		/* 3 Letter <- <((&('$' | '_') ('_' / '$')) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]))> */
		nil,
		/* 4 Spacing <- <((&('\n') '\n') | (&('\r') '\r') | (&('\t') '\t') | (&(' ') ' '))+*> */
		func() bool {
			if memoized, ok := memoization[memoKey{4, position}]; ok {
				return memoizedResult(memoized)
			}
			position142, tokenIndex142 := position, tokenIndex
			{
				position143 := position
			l144:
				{
					position145, tokenIndex145 := position, tokenIndex
					{
						switch buffer[position] {
						case '\n':
							if buffer[position] != rune('\n') {
								goto l145
							}
							position++
						case '\r':
							if buffer[position] != rune('\r') {
								goto l145
							}
							position++
						case '\t':
							if buffer[position] != rune('\t') {
								goto l145
							}
							position++
						default:
							if buffer[position] != rune(' ') {
								goto l145
							}
							position++
						}
					}

				l146:
					{
						position147, tokenIndex147 := position, tokenIndex
						{
							switch buffer[position] {
							case '\n':
								if buffer[position] != rune('\n') {
									goto l147
								}
								position++
							case '\r':
								if buffer[position] != rune('\r') {
									goto l147
								}
								position++
							case '\t':
								if buffer[position] != rune('\t') {
									goto l147
								}
								position++
							default:
								if buffer[position] != rune(' ') {
									goto l147
								}
								position++
							}
						}

						goto l146
					l147:
						position, tokenIndex = position147, tokenIndex147
					}
					goto l144
				l145:
					position, tokenIndex = position145, tokenIndex145
				}
				add(ruleSpacing, position143)
			}
			memoize(4, position142, tokenIndex142, true)
			return true
		},
		/* 5 LetterOrDigit <- <((&('$' | '_') ('_' / '$')) | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]))> */
		func() bool {
			if memoized, ok := memoization[memoKey{5, position}]; ok {
				return memoizedResult(memoized)
			}
			position150, tokenIndex150 := position, tokenIndex
			{
				position151 := position
				{
					switch buffer[position] {
					case '$', '_':
						{
							position153, tokenIndex153 := position, tokenIndex
							if buffer[position] != rune('_') {
								goto l154
							}
							position++
							goto l153
						l154:
							position, tokenIndex = position153, tokenIndex153
							if buffer[position] != rune('$') {
								goto l150
							}
							position++
						}
					l153:
						break
					case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l150
						}
						position++
					case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l150
						}
						position++
					default:
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l150
						}
						position++
					}
				}

				add(ruleLetterOrDigit, position151)
			}
			memoize(5, position150, tokenIndex150, true)
			return true
		l150:
			memoize(5, position150, tokenIndex150, false)
			position, tokenIndex = position150, tokenIndex150
			return false
		},
		/* 6 Keyword <- <(((&('E' | 'e') (('e' / 'E') ('n' / 'N') ('d' / 'D'))) | (&('I' | 'i') (('i' / 'I') ('s' / 'S'))) | (&('P' | 'p') (('p' / 'P') ('a' / 'A') ('c' / 'C') ('k' / 'K') ('a' / 'A') ('g' / 'G') ('e' / 'E'))) | (&('R' | 'r') (('r' / 'R') ('e' / 'E') ('p' / 'P') ('l' / 'L') ('a' / 'A') ('c' / 'C') ('e' / 'E'))) | (&('O' | 'o') (('o' / 'O') ('r' / 'R'))) | (&('C' | 'c') (('c' / 'C') ('r' / 'R') ('e' / 'E') ('a' / 'A') ('t' / 'T') ('e' / 'E')))) !LetterOrDigit)> */
		nil,
		/* 7 CREATE <- <(('c' / 'C') ('r' / 'R') ('e' / 'E') ('a' / 'A') ('t' / 'T') ('e' / 'E') !LetterOrDigit Spacing)> */
		nil,
		/* 8 OR <- <(('o' / 'O') ('r' / 'R') !LetterOrDigit Spacing)> */
		nil,
		/* 9 REPLACE <- <(('r' / 'R') ('e' / 'E') ('p' / 'P') ('l' / 'L') ('a' / 'A') ('c' / 'C') ('e' / 'E') !LetterOrDigit Spacing)> */
		nil,
		/* 10 PACKAGE <- <(('p' / 'P') ('a' / 'A') ('c' / 'C') ('k' / 'K') ('a' / 'A') ('g' / 'G') ('e' / 'E') !LetterOrDigit Spacing)> */
		nil,
		/* 11 IS <- <(('i' / 'I') ('s' / 'S') !LetterOrDigit Spacing)> */
		nil,
		/* 12 END <- <(('e' / 'E') ('n' / 'N') ('d' / 'D') !LetterOrDigit Spacing)> */
		nil,
		/* 13 SEMI <- <(';' Spacing)> */
		nil,
		/* 14 EOT <- <!.> */
		nil,
	}
	p.rules = _rules
	return nil
}
